/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-16 02:03:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.role;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class role_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/shiro-all-1.4.1.jar", Long.valueOf(1567848369347L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1537863568613L));
    _jspx_dependants.put("jar:file:/E:/workspace/gweb/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace/gweb/src/main/webapp/WEB-INF/lib/shiro-all-1.4.1.jar!/META-INF/shiro.tld", Long.valueOf(1555582726000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"img/favicon.ico\" />\r\n");
      out.write("<link href=\"../../css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/formeasyui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../ui/easyui/themes/gray/easyui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/easyui-main.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/icon.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"../../ui/easyui/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../../ui/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script src=\"../../ui/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script src=\"../../js/util.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"bodybody\" style=\"display: none\">\r\n");
      out.write("\t<table class=\"easyui-datagrid\" title=\"\" id=\"roleList\"\r\n");
      out.write("\t\tdata-options=\"singleSelect:true,fitColumns:true,collapsible:false,method:'post',toolbar:'#toolbar'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'name',width:200,align:'center'\">角色列表</th>\r\n");
      out.write("\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\tdata-options=\"field:'roleId',width:400,align:'center',formatter:formatLinkOp\">操作</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"toolbar\" style=\"padding: 2px 5px;\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_shiro_005fhasPermission_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"roleAdddialog\" class=\"easyui-dialog\" title=\"新增角色\"\r\n");
      out.write("\t\tstyle=\"width: 400px; height: 48px; padding: 0px\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t    closed:true,\r\n");
      out.write("\t\t\t    closable:false,\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("                top:50,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-circle-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\tvar roleId ='';\r\n");
      out.write("\t\t\t\t\t\tvar roleName =$('#rolename_add').val();\r\n");
      out.write("\t\t\t\t\t\tvar data = {\r\n");
      out.write("\t\t                 roleId : roleId,\r\n");
      out.write("\t\t                 name : roleName\r\n");
      out.write("\t                    };\r\n");
      out.write("\t                    roleSave(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-utils-s-close',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#roleAdddialog').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table class=\"table-width\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"t\"><span class=\"bitian\">*</span>权限组名称：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ts\"><input name=\"rolename_add\" id=\"rolename_add\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" style=\"width: 260px; height: 28px\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"userSetdialog\" class=\"easyui-dialog\" title=\"人员管理\"\r\n");
      out.write("\t\tstyle=\"width: 550px; height: 400px; padding: 0px\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t    closed:true,\r\n");
      out.write("\t\t\t    closable:true,\r\n");
      out.write("\t\t\t    top:10,\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-utils-s-close',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t$('#userSetdialog').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"tt\" class=\"easyui-tabs\" style=\"height: 385px;\"\r\n");
      out.write("\t\t\t\tdata-options=\"border:false\">\r\n");
      out.write("\t\t\t\t<div title=\"当前\">\r\n");
      out.write("\t\t\t\t\t<table class=\"easyui-datagrid\" id=\"roleuserList\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userId',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'emailaddress',width:160,align:'center'\">账号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userName',width:160,align:'center'\">用户名</th>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div id=\"tbuser\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float: left; padding-left: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"userKey\" class=\"easyui-searchbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsearcher=\"doUserSearch\" prompt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"events:{blur:doUserSearch}\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 130px; vertical-align: middle;\"></input>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"datagrid-btn-separator\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\ticon=\"icon-utils-s-delete\" onclick=\"deleteroleuser()\">删除</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div title=\"可用\" data-options=\"closable:false\"\r\n");
      out.write("\t\t\t\t\tstyle=\"overflow: auto;\">\r\n");
      out.write("\t\t\t\t\t<table class=\"easyui-datagrid\" id=\"remainroleuserList\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userId',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'emailaddress',width:160,align:'center'\">账号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userName',width:160,align:'center'\">用户名</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div id=\"remaintbuser\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float: left; padding-left: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"remainuserKey\" class=\"easyui-searchbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsearcher=\"doRemainUserSearch\" prompt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"events:{blur:doRemainUserSearch}\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 130px; vertical-align: middle;\"></input>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"datagrid-btn-separator\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\ticon=\"icon-utils-s-add\" onclick=\"addroleuser()\">保存</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menuRoledialog\" class=\"easyui-dialog\" title=\"权限管理\"\r\n");
      out.write("\t\tstyle=\"width: 510px; height: 400px; padding: 0px\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t    closed:true,\r\n");
      out.write("\t\t\t    closable:true,\r\n");
      out.write("\t\t\t    top:10,\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-circle-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t                    saveRoleMenu();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-utils-s-close',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\tcolsemenuRoledialog();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class='easyui-layout' style=\"height: 380px; padding: 0px\">\r\n");
      out.write("\t\t\t\t<div style=\"border-right: #e2e2e2 1px solid;\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"width: 230,region:'center',split:false,border:true,collapsible:false,title:'',border:false\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"menutree\" data-options=\"split:false,border:false,title:''\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" name=\"roleId\" id=\"roleId\" value=\"\">\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar roleusrdialog;\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#bodybody').css('display', 'block');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction aaa() {\r\n");
      out.write("\t\talert(222)\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#roleList\").datagrid({\r\n");
      out.write("\t\t\ttitle : '',\r\n");
      out.write("\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\tcollapsible : false,\r\n");
      out.write("\t\t\tpagination : false,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tcheckOnSelect : true,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\turl : getRootPath() + '/role/getRoleEntityList.shtml',\r\n");
      out.write("\t\t\tloadMsg : '数据加载中......',\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tonLoadSuccess : onLoadSuccess\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction saveRoleMenu() {\r\n");
      out.write("\t\tvar menuIds = new Array();\r\n");
      out.write("\t\tvar roleId = $('#roleId').val();\r\n");
      out.write("\t\tvar rows = $('#menutree').tree('getChecked');\r\n");
      out.write("\t\tif (rows != null) {\r\n");
      out.write("\t\t\tfor (var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t// var row=rows[i];\r\n");
      out.write("\t\t\t\tmenuIds.push(rows[i].id);\r\n");
      out.write("\t\t\t\t// alert(rows[i].userId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : getRootPath() + \"/role/saveRoleMenuEntity.shtml\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\ttraditional : \"true\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"menuIds\" : menuIds,\r\n");
      out.write("\t\t\t\t\"roleId\" : roleId,\r\n");
      out.write("\t\t\t\t\"time\" : new Date().getTime()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\ttitle : '提示信息',\r\n");
      out.write("\t\t\t\t\tmsg : '保存成功',\r\n");
      out.write("\t\t\t\t\ttimeout : 5000,\r\n");
      out.write("\t\t\t\t\theight : 100,\r\n");
      out.write("\t\t\t\t\tshowType : 'slide'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction reload() {\r\n");
      out.write("\t\t$(\"#roleList\").datagrid({\r\n");
      out.write("\t\t\turl : getRootPath() + '/role/getRoleEntityList.shtml',\r\n");
      out.write("\t\t\tloadMsg : '数据加载中......',\r\n");
      out.write("\t\t\tmethod : 'post'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteroleuser() {\r\n");
      out.write("\t\t$.messager.confirm('确认', '您确认想要删除记录吗？', function(r) {\r\n");
      out.write("\t\t\tif (r) {\r\n");
      out.write("\t\t\t\tvar userIds = new Array();\r\n");
      out.write("\t\t\t\tvar roleId = $('#roleId').val();\r\n");
      out.write("\t\t\t\tvar rows = $('#roleuserList').datagrid('getChecked');\r\n");
      out.write("\t\t\t\tif (rows != null) {\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t// var row=rows[i];\r\n");
      out.write("\t\t\t\t\t\tuserIds.push(rows[i].userId);\r\n");
      out.write("\t\t\t\t\t\t// alert(rows[i].userId);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : getRootPath() + \"/role/removeUserRoles.shtml\",\r\n");
      out.write("\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\ttraditional : \"true\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\"userIds\" : userIds,\r\n");
      out.write("\t\t\t\t\t\t\"roleId\" : roleId,\r\n");
      out.write("\t\t\t\t\t\t\"time\" : new Date().getTime()\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tdoUserSearch();\r\n");
      out.write("\t\t\t\t\t\tdoRemainUserSearch();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addroleuser() {\r\n");
      out.write("\t\tvar userIds = new Array();\r\n");
      out.write("\t\tvar roleId = $('#roleId').val();\r\n");
      out.write("\t\tvar rows = $('#remainroleuserList').datagrid('getChecked');\r\n");
      out.write("\t\tif (rows != null) {\r\n");
      out.write("\t\t\tfor (var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\tuserIds.push(rows[i].userId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : getRootPath() + \"/role/saveRoleUsersEntity.shtml\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\ttraditional : \"true\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"userIds\" : userIds,\r\n");
      out.write("\t\t\t\t\"roleId\" : roleId,\r\n");
      out.write("\t\t\t\t\"time\" : new Date().getTime()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tdoUserSearch();\r\n");
      out.write("\t\t\t\tdoRemainUserSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction roleSave(data) {\r\n");
      out.write("\t\t$.post(getRootPath() + \"/role/saveRoleEntity.shtml\", data, function(result) {\r\n");
      out.write("\t\t\tif (result && result.result == 1) {\r\n");
      out.write("\t\t\t\treload();\r\n");
      out.write("\t\t\t\t$('#roleAdddialog').dialog('close');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.messager.alert('提示', result.message);\r\n");
      out.write("\t\t\t\t//$('#roleAdddialog').dialog('close');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, \"json\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction roleadd() {\r\n");
      out.write("\t\t$(\"#roleAdddialog\").dialog(\"open\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction formatLinkOp(value, row, index) {\r\n");
      out.write("\t\tvar result = '");
      if (_jspx_meth_shiro_005fhasPermission_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tresult = result + '");
      if (_jspx_meth_shiro_005fhasPermission_005f2(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tresult = result + '");
      if (_jspx_meth_shiro_005fhasPermission_005f3(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\treturn result;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onLoadSuccess(data) {\r\n");
      out.write("\t\t$(\"a[name='settingMenu']\").linkbutton({\r\n");
      out.write("\t\t\ttext : '权限设置',\r\n");
      out.write("\t\t\tplain : true,\r\n");
      out.write("\t\t\ticonCls : 'icon-utils-s-group-service'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"a[name='settingUser']\").linkbutton({\r\n");
      out.write("\t\t\ttext : '人员管理',\r\n");
      out.write("\t\t\tplain : true,\r\n");
      out.write("\t\t\ticonCls : 'icon-utils-s-group-add'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"a[name='settingDelete']\").linkbutton({\r\n");
      out.write("\t\t\ttext : '删除',\r\n");
      out.write("\t\t\tplain : true,\r\n");
      out.write("\t\t\ticonCls : 'icon-utils-s-delete'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction roleSet(roleId) {\r\n");
      out.write("\t\t$(\"#roleId\").val(roleId);\r\n");
      out.write("\t\tif (roleusrdialog == null) {\r\n");
      out.write("\t\t\t$('#rolemenulayout').layout();\r\n");
      out.write("\t\t\t$('#menutree').tree({\r\n");
      out.write("\t\t\t\turl : getRootPath() + '/role/getRoleMenuEntityTree.shtml',\r\n");
      out.write("\t\t\t\tcheckbox : true,\r\n");
      out.write("\t\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t\troleId : $('#roleId').val()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#menutree\").datagrid(\"reload\", {\r\n");
      out.write("\t\t\t\troleId : $('#roleId').val()\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#menuRoledialog\").dialog(\"open\");\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction colsemenuRoledialog() {\r\n");
      out.write("\t\t$(\"#menuRoledialog\").dialog(\"close\");\r\n");
      out.write("\t}\r\n");
      out.write("\tvar roleusergird;\r\n");
      out.write("\tfunction roleUser(roleId) {\r\n");
      out.write("\t\t$(\"#roleId\").val(roleId);\r\n");
      out.write("\t\t$(\"#userKey\").val('');\r\n");
      out.write("\t\tif (roleusergird == null) {\r\n");
      out.write("\t\t\troleusergird = $('#roleuserList').datagrid({\r\n");
      out.write("\t\t\t\turl : getRootPath() + '/role/getUsersRoleEntityList.shtml',\r\n");
      out.write("\t\t\t\tcollapsible : false,\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\trownumbers : true,\r\n");
      out.write("\t\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\t\tcheckOnSelect : true,\r\n");
      out.write("\t\t\t\tselectOnCheck : true,\r\n");
      out.write("\t\t\t\tborder : false,\r\n");
      out.write("\t\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\t\tpageList : [ 10, 20, 50 ],\r\n");
      out.write("\t\t\t\ttoolbar : '#tbuser',\r\n");
      out.write("\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\tnowrap : true,\r\n");
      out.write("\t\t\t\tfit : true,\r\n");
      out.write("\t\t\t\tloadMsg : '数据加载中......',\r\n");
      out.write("\t\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\t\tonBeforeLoad : function(param) {\r\n");
      out.write("\t\t\t\t\tparam.roleId = $('#roleId').val();\r\n");
      out.write("\t\t\t\t\tparam.name = $('#userKey').searchbox('textbox').val();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t\troleId : $('#roleId').val(),\r\n");
      out.write("\t\t\t\t\tname : $('#userKey').searchbox('textbox').val()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tremainroleuserList = $('#remainroleuserList').datagrid({\r\n");
      out.write("\t\t\t\turl : getRootPath() + '/role/getRemainUsersRoleEntityList.shtml',\r\n");
      out.write("\t\t\t\tcollapsible : false,\r\n");
      out.write("\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\trownumbers : true,\r\n");
      out.write("\t\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\t\tcheckOnSelect : true,\r\n");
      out.write("\t\t\t\tselectOnCheck : true,\r\n");
      out.write("\t\t\t\tborder : false,\r\n");
      out.write("\t\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\t\tpageList : [ 10, 20, 50 ],\r\n");
      out.write("\t\t\t\ttoolbar : '#remaintbuser',\r\n");
      out.write("\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\tnowrap : true,\r\n");
      out.write("\t\t\t\tfit : true,\r\n");
      out.write("\t\t\t\tloadMsg : '数据加载中......',\r\n");
      out.write("\t\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\t\tonBeforeLoad : function(param) {\r\n");
      out.write("\t\t\t\t\tparam.roleId = $('#roleId').val();\r\n");
      out.write("\t\t\t\t\tparam.name = $('#remainuserKey').searchbox('textbox').val();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t\troleId : $('#roleId').val(),\r\n");
      out.write("\t\t\t\t\tname : $('#remainuserKey').searchbox('textbox').val()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdoUserSearch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#userSetdialog\").dialog(\"open\");\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction doUserSearch() {\r\n");
      out.write("\t\t//alert($('#userKey').searchbox('textbox').val())\r\n");
      out.write("\t\t//alert($('#userKey').$('#ss').searchbox())\r\n");
      out.write("\t\t//alert($('#userKey').searchbox('textbox').val())\r\n");
      out.write("\t\t$(\"#roleuserList\").datagrid(\"reload\", {\r\n");
      out.write("\t\t\troleId : $('#roleId').val(),\r\n");
      out.write("\t\t\tname : $('#userKey').searchbox('textbox').val()\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction doRemainUserSearch() {\r\n");
      out.write("\t\t//alert( $('#remainuserKey').searchbox('textbox').val())\r\n");
      out.write("\t\t$(\"#remainroleuserList\").datagrid(\"load\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction roleDel(roleId) {\r\n");
      out.write("\t\t$.messager.confirm('确认', '您确认想要删除记录吗？', function(r) {\r\n");
      out.write("\t\t\tif (r) {\r\n");
      out.write("\t\t\t\tvar data = {\r\n");
      out.write("\t\t\t\t\troleId : roleId,\r\n");
      out.write("\t\t\t\t\tname : ''\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t$.post(getRootPath() + \"/role/deleteRoleEntity.shtml\", data, function(result) {\r\n");
      out.write("\t\t\t\t\tif (result && result.result == 1) {\r\n");
      out.write("\t\t\t\t\t\treload();\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert('提示', result.message);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f0 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f0_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f0.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f0.setParent(null);
      // /pages/role/role_list.jsp(35,3) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f0.setName("role:create");
      int _jspx_eval_shiro_005fhasPermission_005f0 = _jspx_th_shiro_005fhasPermission_005f0.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\"\r\n");
          out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-utils-s-add'\" onclick=\"roleadd()\">新增</a>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f0);
      _jspx_th_shiro_005fhasPermission_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f0, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f1 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f1_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f1.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f1.setParent(null);
      // /pages/role/role_list.jsp(321,16) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f1.setName("role:set");
      int _jspx_eval_shiro_005fhasPermission_005f1 = _jspx_th_shiro_005fhasPermission_005f1.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div style=\"float: left;\"><a href=\"#\" name=\"settingMenu\" class=\"easyui-linkbutton\" plain=\"true\"  data-options=\"iconCls:\\'icon-utils-s-group-service\\'\" onclick=\"roleSet(\\'' + value + '\\')\">权限设置</a> </div>");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f1);
      _jspx_th_shiro_005fhasPermission_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f1, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f2 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f2_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f2.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f2.setParent(null);
      // /pages/role/role_list.jsp(322,21) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f2.setName("role:user");
      int _jspx_eval_shiro_005fhasPermission_005f2 = _jspx_th_shiro_005fhasPermission_005f2.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div class=\"datagrid-btn-separator\"></div><div style=\"float: left;\"><a href=\"#\"  name=\"settingUser\" class=\"easyui-linkbutton\" plain=\"true\" icon=\"icon-utils-s-group-add\" onclick=\"roleUser(\\'' + value + '\\')\">人员管理</a> </div>");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f2);
      _jspx_th_shiro_005fhasPermission_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f2, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f3 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f3_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f3.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f3.setParent(null);
      // /pages/role/role_list.jsp(323,21) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f3.setName("role:delete");
      int _jspx_eval_shiro_005fhasPermission_005f3 = _jspx_th_shiro_005fhasPermission_005f3.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div class=\"datagrid-btn-separator\"></div><div style=\"float: left;\"><a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\" icon=\"icon-utils-s-delete\" name=\"settingDelete\" onclick=\"roleDel(\\'' + value + '\\')\">删除</a> </div>");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f3);
      _jspx_th_shiro_005fhasPermission_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f3, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f3_reused);
    }
    return false;
  }
}
