/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-18 06:29:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fmultipleselect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/shiro-all-1.4.1.jar", Long.valueOf(1567848369347L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1537863568613L));
    _jspx_dependants.put("jar:file:/E:/workspace/gweb/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace/gweb/src/main/webapp/WEB-INF/lib/shiro-all-1.4.1.jar!/META-INF/shiro.tld", Long.valueOf(1555582726000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"img/favicon.ico\" />\r\n");
      out.write("<link href=\"../../css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/formeasyui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../ui/easyui/themes/gray/easyui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/easyui-main.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../css/icon.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../../js/constant .js\"></script>\r\n");
      out.write("<script src=\"../../js/util.js\"></script>\r\n");
      out.write("<script src=\"../../ui/easyui/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../../ui/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script src=\"../../ui/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"mainLayout\" style=\"display: none\" class=\"easyui-layout\"\r\n");
      out.write("\tdata-options=\"fit:true\">\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tdata-options=\"region:'north',split:false,border:true,collapsible:false,title:''\"\r\n");
      out.write("\t\tid=\"west\" style=\"position: relative; border-right: #e2e2e2 1px solid;\">\r\n");
      out.write("\t\t<table class=\"table-width\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"t\" style=\"width: 80px;\">部门：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ts\" style=\"width: 210px;\"><input name=\"parentId\"\r\n");
      out.write("\t\t\t\t\tid=\"parentId\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 200px; height: 28px\" /></td>\r\n");
      out.write("\t\t\t\t<td class=\"t\" style=\"width: 80px;\">用户名称：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ts\" style=\"width: 210px;\"><input\r\n");
      out.write("\t\t\t\t\tname=\"userName_search\" id=\"userName_search\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 200px; height: 28px\" /></td>\r\n");
      out.write("\t\t\t\t<td><div style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-utils-s-search\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"dosearch()\">查询</a>\r\n");
      out.write("\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'center',border:false\">\r\n");
      out.write("\t\t<table style=\"width: 790px; height: 96%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width: 350px; height: 100%\">\r\n");
      out.write("\t\t\t\t\t<table class=\"easyui-datagrid\" id=\"userList\" title='所有用户'\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"rownumbers:true,idField: 'userId',fit:true\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userId',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'emailaddress',width:145,align:'center'\">账号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userName',width:145,align:'center'\">用户名称</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 56px;\"><div style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"doselected()\">&nbsp;&nbsp;>>&nbsp;&nbsp;</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"dodelselected()\">&nbsp;&nbsp;<<&nbsp;&nbsp;</a>\r\n");
      out.write("\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 350px; height: 100%\">\r\n");
      out.write("\t\t\t\t\t<table class=\"easyui-datagrid\" id=\"selectuseruserList\" title='已选用户'\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"rownumbers:true,idField: 'userId',fit:true\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userId',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'emailaddress',width:100,align:'center'\">账号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-options=\"field:'userName',width:120,align:'center'\">用户名称</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"id\" id=\"id\" value=\"0\">\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#mainLayout').css('display', 'block');\r\n");
      out.write("\t});\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#parentId').combotree({\r\n");
      out.write("\t\t\turl : getRootPath() + '/organization/getOrganizationEntityTreeWithSelect.shtml',\r\n");
      out.write("\t\t\tonLoadSuccess : function(node, data) {\r\n");
      out.write("\t\t\t\tif ($(\"#parentId\").combotree(\"getValue\") == '') {\r\n");
      out.write("\t\t\t\t\t$('#parentId').combotree('setValue', data[0].id);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tuserList = $('#userList').datagrid({\r\n");
      out.write("\t\t\turl : getRootPath() + '/user/getUsersEntityList.shtml',\r\n");
      out.write("\t\t\tcollapsible : false,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\tcheckOnSelect : true,\r\n");
      out.write("\t\t\tselectOnCheck : true,\r\n");
      out.write("\t\t\tborder : true,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageList : [ 10, 20, 50 ],\r\n");
      out.write("\t\t\t//toolbar : '#remaintbuser',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\t// toolbar : '#tbuser',\r\n");
      out.write("\t\t\tloadMsg : '数据加载中......',\r\n");
      out.write("\t\t\tfitColumns : false,\r\n");
      out.write("\t\t\tonBeforeLoad : function(param) {\r\n");
      out.write("\t\t\t\t// param.ORGANIZATIONID = $(\"#parentId\").tree(\"getValue\");\r\n");
      out.write("\t\t\t\tparam.KEYNAME = $('#userName_search').val();\r\n");
      out.write("\t\t\t\tparam.ORGANIZATIONID = $(\"#parentId\").combotree(\"getValue\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar p = $(\"#userList\").datagrid(\"getPager\");\r\n");
      out.write("\t\t$(p).pagination({\r\n");
      out.write("\t\t\t\"displayMsg\" : \"\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#mainLayout').layout(\"resize\");\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction dosearch() {\r\n");
      out.write("\t\t$(\"#userList\").datagrid(\"reload\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction doselected() {\r\n");
      out.write("\t\tvar nodes = $('#userList').datagrid('getChecked');\r\n");
      out.write("\t\tif (nodes != null) {\r\n");
      out.write("\t\t\t//alert(nodes.length)\r\n");
      out.write("\t\t\tfor (var i = 0; i < nodes.length; i++) {\r\n");
      out.write("\t\t\t\tvar node = nodes[i];\r\n");
      out.write("\t\t\t\t//alert( node.userId)\r\n");
      out.write("\t\t\t\tvar rowData = $('#selectuseruserList').datagrid('getRowIndex', node.userId);\r\n");
      out.write("\t\t\t\t//alert(rowData)\r\n");
      out.write("\t\t\t\tif (rowData == -1) {\r\n");
      out.write("\t\t\t\t\t$('#selectuseruserList').datagrid('insertRow', {\r\n");
      out.write("\t\t\t\t\t\tindex : 0,\r\n");
      out.write("\t\t\t\t\t\trow : node\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction dodelselected() {\r\n");
      out.write("\t\tvar nodes = $('#selectuseruserList').datagrid('getChecked');\r\n");
      out.write("\r\n");
      out.write("\t\tif (nodes != null) {\r\n");
      out.write("\t\t\tvar copyRows = [];\r\n");
      out.write("\t\t\tfor (var j = 0; j < nodes.length; j++) {\r\n");
      out.write("\t\t\t\tcopyRows.push(nodes[j]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor (var i = 0; i < copyRows.length; i++) {\r\n");
      out.write("\t\t\t\tvar node = copyRows[i];\r\n");
      out.write("\t\t\t\tvar rowData = $('#selectuseruserList').datagrid('getRowIndex', node.userId);\r\n");
      out.write("\t\t\t\tif (rowData != -1) {\r\n");
      out.write("\t\t\t\t\t$('#selectuseruserList').datagrid('deleteRow', rowData);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//refreshRow\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
