/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2020-01-07 07:29:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.police.place;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class placelist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/shiro-all-1.4.1.jar", Long.valueOf(1567848369347L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1537863568613L));
    _jspx_dependants.put("jar:file:/E:/workspace/gweb/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace/gweb/src/main/webapp/WEB-INF/lib/shiro-all-1.4.1.jar!/META-INF/shiro.tld", Long.valueOf(1555582726000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"img/favicon.ico\" />\r\n");
      out.write("<link href=\"../../../css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../../css/formeasyui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../../ui/easyui/themes/gray/easyui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../../css/easyui-main.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../../css/icon.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../../../js/util.js\"></script>\r\n");
      out.write("<script src=\"../../../js/constant.js\"></script>\r\n");
      out.write("<script src=\"../../../ui/easyui/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../../../ui/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script src=\"../../../ui/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"mainLayout\" style=\"display: none\" class=\"easyui-layout\"\r\n");
      out.write("\tdata-options=\"fit:true\">\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tdata-options=\"region:'north',split:false,border:true,collapsible:false,title:''\"\r\n");
      out.write("\t\tid=\"west\" style=\"width: 100%; height: 66px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<form id=\"searchForm\">\r\n");
      out.write("\t\t\t<table class=\"table-width\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"t\" style=\"width: 80px;\">名称：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ts\" style=\"width: 220px;\"><input name=\"name_search\"\r\n");
      out.write("\t\t\t\t\t\tid=\"name_search\" class=\"form-control\" style=\"width: 200px;\" /></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"t\" style=\"width: 80px;\">辖区：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ts\" style=\"width: 220px;\"><input name=\"parentId\"\r\n");
      out.write("\t\t\t\t\t\tid=\"parentId\" class=\"form-control\" style=\"width: 200px;\" /></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: left;\" rowspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"t\" style=\"width: 80px;\">场所类型：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ts\" style=\"width: 220px;\"><select\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-combobox\" id=\"placeType_search\"\r\n");
      out.write("\t\t\t\t\t\tname=\"'placeType_search\" style=\"width: 200px;\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<td class=\"t\" style=\"width: 80px;\">功能类型：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ts\" style=\"width: 220px;\"><select\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-combobox\" id=\"functiontype_search\"\r\n");
      out.write("\t\t\t\t\t\tname=\"'functiontype_search\" style=\"width: 200px;\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div data-options=\"region:'center',border:false\" style=\"width: 100%;\">\r\n");
      out.write("\t\t<table class=\"easyui-datagrid\" id=\"userList\"\r\n");
      out.write("\t\t\tdata-options=\"idField:'id',rownumbers:true,toolbar:'#toolbar_custom', fit:true,fitColumns:true\"\r\n");
      out.write("\t\t\tstyle=\"width: 100%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- <th data-options=\"field:'id',checkbox:true,fixed:true\"></th> -->\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'id',width:60,align:'center',formatter:formatLinkOp\">操作</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'eqpName',width:200,align:'center'\">辖区</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'name',width:280,align:'center'\">名称</th>\r\n");
      out.write("\t\t\t\t\t<th data-options=\"field:'code',width:180,align:'center',fixed:true\">编号</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'placeTypeShowValue',width:80,align:'center',fixed:true\">场所类型</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'videoCount',width:80,align:'center',fixed:true\">摄像机数量</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'createDateStr',width:80,align:'center',fixed:true\">创建日期</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"toolbar_custom\"\r\n");
      out.write("\t\tstyle=\"height: 36px; width: 100%; padding: 3px 11px; background: #fafafa;\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_shiro_005fhasPermission_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_shiro_005fhasPermission_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"exeTime\"\r\n");
      out.write("\t\t\tstyle=\"font-size: 10px; float: right; margin-top: 10px;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- viewWindow -->\r\n");
      out.write("\t<div id=\"viewWindow\" class=\"easyui-window\" title=\"\"\r\n");
      out.write("\t\tdata-options=\"closed:true,\r\n");
      out.write("\t\t\t    closable:false,\r\n");
      out.write("\t\t\t    top:0,\r\n");
      out.write("\t\t\t    width:710,\r\n");
      out.write("\t\t\t    doSize:true,\r\n");
      out.write("\t\t\t    title:'',\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("\t\thref:'place_view.jsp'\"\r\n");
      out.write("\t\tstyle=\"width: 710px; height: 400; padding: 0px\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"adddialog\" class=\"easyui-dialog\" title=\"新增用户\"\r\n");
      out.write("\t\tstyle=\"width: 600px; height: 150px; padding: 0px\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t    closed:true,\r\n");
      out.write("\t\t\t    closable:false,\r\n");
      out.write("                top:50,\r\n");
      out.write("                href:'user_add.jsp',\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\tdraggable:false,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-circle-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t                    entitySave();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'关闭',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-utils-s-close',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#adddialog').dialog('close');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"id\" id=\"id\" value=\"0\">\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("     function closeview(){\r\n");
      out.write("    \t $('#viewWindow').dialog('close');\r\n");
      out.write("     }\r\n");
      out.write("\tfunction add() {\r\n");
      out.write("\t\t$(\"#adddialog\").dialog(\"open\");\r\n");
      out.write("\t\t$('#entityAddForm').form('reset')\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction dosearch() {\r\n");
      out.write("\t\t$(\"#userList\").datagrid(\"reload\");\r\n");
      out.write("\t}\r\n");
      out.write("\tvar roleusrdialog;\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#mainLayout').css('display', 'block');\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction formatLinkOp(value, row, index) {\r\n");
      out.write("\t\tvar result = '<div style=\"float: left;\"><a href=\"#\" name=\"viewdetail\" class=\"easyui-linkbutton\" plain=\"true\"  data-options=\"iconCls:\\'icon-utils-s-group-service\\'\" onclick=\"viewInfo(\\'' + value + '\\',\\'' + index + '\\')\">详细</a></div>';\r\n");
      out.write("\t\treturn result;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction viewInfo(id, index) {\r\n");
      out.write("\t\t//alert(index)\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#viewWindow\").dialog({\r\n");
      out.write("\t\t\tleft : 280,\r\n");
      out.write("\t\t\theight : $(\"body[class='easyui-layout layout panel-noscroll']\").css('height'),\r\n");
      out.write("\t\t\ttop : 0,\r\n");
      out.write("\t\t\twidth : document.documentElement.clientWidth - 275,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tanimate : true,\r\n");
      out.write("\t\t\tonLoad : function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}).dialog(\"open\");\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#placeType_search').combobox({\r\n");
      out.write("\t\t\turl : getRootPath() + '/systemData/getSystemDataEntityListWithSelect.shtml',\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t\"dataCode\" : SystemData.PLACETYPE,\r\n");
      out.write("\t\t\t\t\"showAll\" : 1\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshowItemIcon : true,\r\n");
      out.write("\t\t\tpanelHeight : 'auto',\r\n");
      out.write("\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\ttextField : 'text'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#functiontype_search').combobox({\r\n");
      out.write("\t\t\turl : getRootPath() + '/systemData/getSystemDataEntityListWithSelect.shtml',\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t\"dataCode\" : SystemData.FUNCTIONTYPE,\r\n");
      out.write("\t\t\t\t\"showAll\" : 1\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tpanelHeight : 'auto',\r\n");
      out.write("\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\ttextField : 'text'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#parentId').combotree({\r\n");
      out.write("\t\t\turl : getRootPath() + '/organization/getOrganizationEntityTreeWithSelect.shtml',\r\n");
      out.write("\t\t\tpanelHeight : 'auto'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tuserList = $('#userList').datagrid({\r\n");
      out.write("\t\t\turl : getRootPath() + '/place/getPlaceEntityList.shtml',\r\n");
      out.write("\t\t\tcollapsible : false,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\tcheckOnSelect : true,\r\n");
      out.write("\t\t\tselectOnCheck : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageList : [ 10, 20, 50 ],\r\n");
      out.write("\t\t\t//toolbar : '#remaintbuser',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\t// toolbar : '#tbuser',\r\n");
      out.write("\t\t\tloadMsg : '数据加载中......',\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tonBeforeLoad : function(param) {\r\n");
      out.write("\t\t\t\tparam.ORGANIZATIONID = $(\"#parentId\").combotree(\"getValue\");\r\n");
      out.write("\t\t\t\tparam.NAME = $('#userName_search').val();\r\n");
      out.write("\t\t\t\tparam.TYPE = $('#placeType_search').val();\r\n");
      out.write("\t\t\t\tparam.FUNCTIONTYPE = $('#functiontype_search').val();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\tORGANIZATIONID : $(\"#parentId\").combotree(\"getValue\"),\r\n");
      out.write("\t\t\t\tNAME : $('#userName_search').val(),\r\n");
      out.write("\t\t\t\tTYPE : $('#placeType_search').val(),\r\n");
      out.write("\t\t\t\tFUNCTIONTYPE : $('#functiontype_search').val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonLoadSuccess : function onLoadSuccess(data) {\r\n");
      out.write("\t\t\t\tvar trs = $(this).prev().find('div.datagrid-body').find('tr');\r\n");
      out.write("\t\t\t\t$(\"a[name='viewdetail']\").linkbutton({\r\n");
      out.write("\t\t\t\t\ttext : '详细',\r\n");
      out.write("\t\t\t\t\tplain : true,\r\n");
      out.write("\t\t\t\t\ticonCls : 'icon-system-view'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tvar timeunits = 's';\r\n");
      out.write("\t\t\t\tdata.exeTime = data.exeTime / 1000;\r\n");
      out.write("\t\t\t\tvar extclass = \"progressbar-text-orange\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('#exeTime').html(\"<span>响应时间:</span><span style='margin-top:20px;' class='\"+extclass+ \"' >&nbsp;\" + data.exeTime + timeunits + \"</span>\")\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#mainLayout').layout(\"resize\");\r\n");
      out.write("\t\t$('#mainLayout').layout('panel', 'center').panel({\r\n");
      out.write("\t\t\tonResize : function(width, height) {\r\n");
      out.write("\t\t\t\tif ($(\"#viewWindow\").parent().is(\":hidden\")) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#viewWindow').panel('resize', {\r\n");
      out.write("\t\t\t\t\t\tleft : 280,\r\n");
      out.write("\t\t\t\t\t\theight : $(\"body[class='easyui-layout layout panel-noscroll']\").css('height'),\r\n");
      out.write("\t\t\t\t\t\ttop : 0,\r\n");
      out.write("\t\t\t\t\t\twidth : document.documentElement.clientWidth - 275,\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f0 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f0_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f0.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f0.setParent(null);
      // /pages/police/place/placelist.jsp(81,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f0.setName("org:create");
      int _jspx_eval_shiro_005fhasPermission_005f0 = _jspx_th_shiro_005fhasPermission_005f0.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div style=\"float: left;\">\r\n");
          out.write("\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\"\r\n");
          out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-utils-s-search'\" onclick=\"dosearch()\">查询</a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"datagrid-btn-separator\"></div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f0);
      _jspx_th_shiro_005fhasPermission_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f0, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f1 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f1_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f1.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f1.setParent(null);
      // /pages/police/place/placelist.jsp(90,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f1.setName("org:create");
      int _jspx_eval_shiro_005fhasPermission_005f1 = _jspx_th_shiro_005fhasPermission_005f1.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div style=\"float: left;\">\r\n");
          out.write("\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\"\r\n");
          out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-utils-s-excel'\" onclick=\"remove()\">导出</a>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f1);
      _jspx_th_shiro_005fhasPermission_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f1, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f1_reused);
    }
    return false;
  }
}
